name: go-snaps-helloworld
version: git
summary:  A starter example of how to package a go app into a snap
description: |
  A starter example of how to package a go app into a snap

grade: devel
confinement: devmode

parts:
  go-snaps-helloworld:
    source: .
    plugin: go
    go-importpath: github.com/nmrshll/snapcraft-go-helloworld

apps:
  go-snaps-helloworld:
    command: snapcraft-go-helloworld